site_name: Manel-Institut Pedralbes
nav:
    - Home: index.md
    - Assignatures de l'institut: assignatures.md
    - Menjar preferit: menjar.md
    - HOLA: hola.md
    - Como se añade un footer a todas las paginas: respuesta.md
theme: readthedocs
